module.exports = [
    {
        name: "Suresh Kumar",
        age: 32,
        gender: "Male",
        occupation: "Engineer",
        city: "Chennai",
        state: "Tamil Nadu",
    },
    {
        name: "Priya Rajan",
        age: 28,
        gender: "Female",
        occupation: "Doctor",
        city: "Coimbatore",
        state: "Tamil Nadu",
    },
    {
        name: "Rajesh Menon",
        age: 35,
        gender: "Male",
        occupation: "Teacher",
        city: "Madurai",
        state: "Tamil Nadu",
    },
    {
        name: "Deepa Raman",
        age: 29,
        gender: "Female",
        occupation: "Software Developer",
        city: "Tiruchirappalli",
        state: "Tamil Nadu",
    },
    {
        name: "Karthik Subramanian",
        age: 27,
        gender: "Male",
        occupation: "Accountant",
        city: "Salem",
        state: "Tamil Nadu",
    },
    {
        name: "Lakshmi Natarajan",
        age: 33,
        gender: "Female",
        occupation: "Nurse",
        city: "Tirunelveli",
        state: "Tamil Nadu",
    },
    {
        name: "Raj Kumar",
        age: 45,
        gender: "Male",
        occupation: "Business Owner",
        city: "Tiruppur",
        state: "Tamil Nadu",
    },
    {
        name: "Saranya Krishnan",
        age: 31,
        gender: "Female",
        occupation: "Marketing Manager",
        city: "Erode",
        state: "Tamil Nadu",
    },
    {
        name: "Arjun Patel",
        age: 29,
        gender: "Male",
        occupation: "Architect",
        city: "Vellore",
        state: "Tamil Nadu",
    },
    {
        name: "Meena Sundaram",
        age: 40,
        gender: "Female",
        occupation: "Banker",
        city: "Nagercoil",
        state: "Tamil Nadu",
    },
    {
        name: "Prakash Raj",
        age: 37,
        gender: "Male",
        occupation: "Lawyer",
        city: "Thanjavur",
        state: "Tamil Nadu",
    },
    {
        name: "Anita Sharma",
        age: 26,
        gender: "Female",
        occupation: "Journalist",
        city: "Tiruvannamalai",
        state: "Tamil Nadu",
    },
    {
        name: "Ganesh Iyer",
        age: 34,
        gender: "Male",
        occupation: "Chef",
        city: "Karur",
        state: "Tamil Nadu",
    },
    {
        name: "Manju Raghavan",
        age: 30,
        gender: "Female",
        occupation: "Pharmacist",
        city: "Dindigul",
        state: "Tamil Nadu",
    },
    {
        name: "Vijay Kumar",
        age: 28,
        gender: "Male",
        occupation: "Software Engineer",
        city: "Tirupathur",
        state: "Tamil Nadu",
    },
    {
        name: "Geeta Raj",
        age: 42,
        gender: "Female",
        occupation: "Teacher",
        city: "Namakkal",
        state: "Tamil Nadu",
    },
    {
        name: "Ravi Shankar",
        age: 39,
        gender: "Male",
        occupation: "Doctor",
        city: "Pollachi",
        state: "Tamil Nadu",
    },
    {
        name: "Priyanka Reddy",
        age: 27,
        gender: "Female",
        occupation: "Engineer",
        city: "Hosur",
        state: "Tamil Nadu",
    },
    {
        name: "Senthil Kumar",
        age: 31,
        gender: "Male",
        occupation: "Banker",
        city: "Krishnagiri",
        state: "Tamil Nadu",
    },
    {
        name: "Anjali Nair",
        age: 29,
        gender: "Female",
        occupation: "Graphic Designer",
        city: "Cuddalore",
        state: "Tamil Nadu",
    },
];
